/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__ht
#define __PYX_HAVE__ht

#include "Python.h"
struct Move;

/* "ht.pyx":13
 * 
 * 
 * cdef public struct Move:             # <<<<<<<<<<<<<<
 * 	int piece
 * 	int start
 */
struct Move {
  int piece;
  int start;
  int end;
};

#ifndef __PYX_HAVE_API__ht

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__ht */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initht(void);
#else
PyMODINIT_FUNC PyInit_ht(void);
#endif

#endif /* !__PYX_HAVE__ht */
